[package]
name = "usg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
clap = "3.1.18"
csv = "1.1.6"
pcap = "0.9.2"
procfs = "0.12.0"
